// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_extras.proto

// Protobuf Java Version: 3.25.0
package edu.cmu.cs.roundtrip.protos;

public final class ClientExtras {
  private ClientExtras() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:client.Location)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code client.Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageLite<
          Location, Location.Builder> implements
      // @@protoc_insertion_point(message_implements:client.Location)
      LocationOrBuilder {
    private Location() {
    }
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <code>double latitude = 1;</code>
     * @param value The latitude to set.
     */
    private void setLatitude(double value) {
      
      latitude_ = value;
    }
    /**
     * <code>double latitude = 1;</code>
     */
    private void clearLatitude() {

      latitude_ = 0D;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <code>double longitude = 2;</code>
     * @param value The longitude to set.
     */
    private void setLongitude(double value) {
      
      longitude_ = value;
    }
    /**
     * <code>double longitude = 2;</code>
     */
    private void clearLongitude() {

      longitude_ = 0D;
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(edu.cmu.cs.roundtrip.protos.ClientExtras.Location prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code client.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.cmu.cs.roundtrip.protos.ClientExtras.Location, Builder> implements
        // @@protoc_insertion_point(builder_implements:client.Location)
        edu.cmu.cs.roundtrip.protos.ClientExtras.LocationOrBuilder {
      // Construct using edu.cmu.cs.roundtrip.protos.ClientExtras.Location.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>double latitude = 1;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <code>double latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <code>double longitude = 2;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <code>double longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:client.Location)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new edu.cmu.cs.roundtrip.protos.ClientExtras.Location();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "latitude_",
              "longitude_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<edu.cmu.cs.roundtrip.protos.ClientExtras.Location> parser = PARSER;
          if (parser == null) {
            synchronized (edu.cmu.cs.roundtrip.protos.ClientExtras.Location.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<edu.cmu.cs.roundtrip.protos.ClientExtras.Location>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:client.Location)
    private static final edu.cmu.cs.roundtrip.protos.ClientExtras.Location DEFAULT_INSTANCE;
    static {
      Location defaultInstance = new Location();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Location.class, defaultInstance);
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Location> PARSER;

    public static com.google.protobuf.Parser<Location> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ExtrasOrBuilder extends
      // @@protoc_insertion_point(interface_extends:client.Extras)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.client.Location current_location = 1;</code>
     * @return Whether the currentLocation field is set.
     */
    boolean hasCurrentLocation();
    /**
     * <code>.client.Location current_location = 1;</code>
     * @return The currentLocation.
     */
    edu.cmu.cs.roundtrip.protos.ClientExtras.Location getCurrentLocation();

    /**
     * <code>optional string annotation_text = 2;</code>
     * @return Whether the annotationText field is set.
     */
    boolean hasAnnotationText();
    /**
     * <code>optional string annotation_text = 2;</code>
     * @return The annotationText.
     */
    java.lang.String getAnnotationText();
    /**
     * <code>optional string annotation_text = 2;</code>
     * @return The bytes for annotationText.
     */
    com.google.protobuf.ByteString
        getAnnotationTextBytes();
  }
  /**
   * Protobuf type {@code client.Extras}
   */
  public  static final class Extras extends
      com.google.protobuf.GeneratedMessageLite<
          Extras, Extras.Builder> implements
      // @@protoc_insertion_point(message_implements:client.Extras)
      ExtrasOrBuilder {
    private Extras() {
      annotationText_ = "";
    }
    private int bitField0_;
    public static final int CURRENT_LOCATION_FIELD_NUMBER = 1;
    private edu.cmu.cs.roundtrip.protos.ClientExtras.Location currentLocation_;
    /**
     * <code>.client.Location current_location = 1;</code>
     */
    @java.lang.Override
    public boolean hasCurrentLocation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.client.Location current_location = 1;</code>
     */
    @java.lang.Override
    public edu.cmu.cs.roundtrip.protos.ClientExtras.Location getCurrentLocation() {
      return currentLocation_ == null ? edu.cmu.cs.roundtrip.protos.ClientExtras.Location.getDefaultInstance() : currentLocation_;
    }
    /**
     * <code>.client.Location current_location = 1;</code>
     */
    private void setCurrentLocation(edu.cmu.cs.roundtrip.protos.ClientExtras.Location value) {
      value.getClass();
  currentLocation_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.client.Location current_location = 1;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeCurrentLocation(edu.cmu.cs.roundtrip.protos.ClientExtras.Location value) {
      value.getClass();
  if (currentLocation_ != null &&
          currentLocation_ != edu.cmu.cs.roundtrip.protos.ClientExtras.Location.getDefaultInstance()) {
        currentLocation_ =
          edu.cmu.cs.roundtrip.protos.ClientExtras.Location.newBuilder(currentLocation_).mergeFrom(value).buildPartial();
      } else {
        currentLocation_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.client.Location current_location = 1;</code>
     */
    private void clearCurrentLocation() {  currentLocation_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int ANNOTATION_TEXT_FIELD_NUMBER = 2;
    private java.lang.String annotationText_;
    /**
     * <code>optional string annotation_text = 2;</code>
     * @return Whether the annotationText field is set.
     */
    @java.lang.Override
    public boolean hasAnnotationText() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string annotation_text = 2;</code>
     * @return The annotationText.
     */
    @java.lang.Override
    public java.lang.String getAnnotationText() {
      return annotationText_;
    }
    /**
     * <code>optional string annotation_text = 2;</code>
     * @return The bytes for annotationText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAnnotationTextBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(annotationText_);
    }
    /**
     * <code>optional string annotation_text = 2;</code>
     * @param value The annotationText to set.
     */
    private void setAnnotationText(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      annotationText_ = value;
    }
    /**
     * <code>optional string annotation_text = 2;</code>
     */
    private void clearAnnotationText() {
      bitField0_ = (bitField0_ & ~0x00000002);
      annotationText_ = getDefaultInstance().getAnnotationText();
    }
    /**
     * <code>optional string annotation_text = 2;</code>
     * @param value The bytes for annotationText to set.
     */
    private void setAnnotationTextBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      annotationText_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(edu.cmu.cs.roundtrip.protos.ClientExtras.Extras prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code client.Extras}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.cmu.cs.roundtrip.protos.ClientExtras.Extras, Builder> implements
        // @@protoc_insertion_point(builder_implements:client.Extras)
        edu.cmu.cs.roundtrip.protos.ClientExtras.ExtrasOrBuilder {
      // Construct using edu.cmu.cs.roundtrip.protos.ClientExtras.Extras.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.client.Location current_location = 1;</code>
       */
      @java.lang.Override
      public boolean hasCurrentLocation() {
        return instance.hasCurrentLocation();
      }
      /**
       * <code>.client.Location current_location = 1;</code>
       */
      @java.lang.Override
      public edu.cmu.cs.roundtrip.protos.ClientExtras.Location getCurrentLocation() {
        return instance.getCurrentLocation();
      }
      /**
       * <code>.client.Location current_location = 1;</code>
       */
      public Builder setCurrentLocation(edu.cmu.cs.roundtrip.protos.ClientExtras.Location value) {
        copyOnWrite();
        instance.setCurrentLocation(value);
        return this;
        }
      /**
       * <code>.client.Location current_location = 1;</code>
       */
      public Builder setCurrentLocation(
          edu.cmu.cs.roundtrip.protos.ClientExtras.Location.Builder builderForValue) {
        copyOnWrite();
        instance.setCurrentLocation(builderForValue.build());
        return this;
      }
      /**
       * <code>.client.Location current_location = 1;</code>
       */
      public Builder mergeCurrentLocation(edu.cmu.cs.roundtrip.protos.ClientExtras.Location value) {
        copyOnWrite();
        instance.mergeCurrentLocation(value);
        return this;
      }
      /**
       * <code>.client.Location current_location = 1;</code>
       */
      public Builder clearCurrentLocation() {  copyOnWrite();
        instance.clearCurrentLocation();
        return this;
      }

      /**
       * <code>optional string annotation_text = 2;</code>
       * @return Whether the annotationText field is set.
       */
      @java.lang.Override
      public boolean hasAnnotationText() {
        return instance.hasAnnotationText();
      }
      /**
       * <code>optional string annotation_text = 2;</code>
       * @return The annotationText.
       */
      @java.lang.Override
      public java.lang.String getAnnotationText() {
        return instance.getAnnotationText();
      }
      /**
       * <code>optional string annotation_text = 2;</code>
       * @return The bytes for annotationText.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAnnotationTextBytes() {
        return instance.getAnnotationTextBytes();
      }
      /**
       * <code>optional string annotation_text = 2;</code>
       * @param value The annotationText to set.
       * @return This builder for chaining.
       */
      public Builder setAnnotationText(
          java.lang.String value) {
        copyOnWrite();
        instance.setAnnotationText(value);
        return this;
      }
      /**
       * <code>optional string annotation_text = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnnotationText() {
        copyOnWrite();
        instance.clearAnnotationText();
        return this;
      }
      /**
       * <code>optional string annotation_text = 2;</code>
       * @param value The bytes for annotationText to set.
       * @return This builder for chaining.
       */
      public Builder setAnnotationTextBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAnnotationTextBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:client.Extras)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new edu.cmu.cs.roundtrip.protos.ClientExtras.Extras();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "currentLocation_",
              "annotationText_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
                "\u1208\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<edu.cmu.cs.roundtrip.protos.ClientExtras.Extras> parser = PARSER;
          if (parser == null) {
            synchronized (edu.cmu.cs.roundtrip.protos.ClientExtras.Extras.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<edu.cmu.cs.roundtrip.protos.ClientExtras.Extras>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:client.Extras)
    private static final edu.cmu.cs.roundtrip.protos.ClientExtras.Extras DEFAULT_INSTANCE;
    static {
      Extras defaultInstance = new Extras();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Extras.class, defaultInstance);
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.Extras getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Extras> PARSER;

    public static com.google.protobuf.Parser<Extras> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
